### ISSUE TITLE
[PE-D][Tester C] Error message for add employee command does not match user behavior

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T17-2/tp#250]
It appears that the error message should be "Compulsory fields are missing"

But the error message I get is that my input field for id is not positive. 

![Screenshot 2023-03-31 at 2.42.28 PM.png](https://raw.githubusercontent.com/jayhee3/ped/main/files/1a6fe051-b614-4050-9fc5-ca1827084104.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: jayhee3/ped#5

**Comment by kennethk-1201** [comment]
wrong output, need to fix
