### ISSUE TITLE
[PE-D][Tester D] Confusing UI because leave and employee components are not updated together

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T17-2/tp#258]
While the Department-Employee-Leave organisation structure is appreciated, it might be a little confusing for the user after performing a series of commands. 

![image.png](https://raw.githubusercontent.com/joyngjr/ped/main/files/9da61180-3b91-4920-93ea-f59ec7be7ddd.png)

For example, after deleting a leave on a particular date, the leaves section shows that no one is taking leaves on 9 mar. However, after using another command to look for all employees taking leaves on 10 mar, it lists the leave of 1 employee. This seems to be out of sync with the leaves section, perhaps it would be better for leaves to be updated together with employee? It may be confusing for a new user who does not know why there are people on leave, even though there is no one taking leave in the right display.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: joyngjr/ped#10

**Comment by kennethk-1201** [comment]
purpose of `sa` command

**Comment by kennethk-1201** [comment]
update in UG

**Comment by kennethk-1201** [comment]
consistency and feedback to user
