### ISSUE TITLE
[PE-D][Tester A] UG says Employee Names must be comprised of alphabetical characters, but the command output error says otherwise

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T17-2/tp#270]
Entered the invalid input below:

![image.png](https://raw.githubusercontent.com/axmszr/ped/main/files/0c1856ab-7155-4f86-a219-9c4c40a2a1c1.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: axmszr/ped#9

**Comment by kennethk-1201** [comment]
update UG
